### ISSUE TITLE
Indonesian Translation Tracking

### ISSUE THREAD

**Issue by CikiMomogi** [CikiMomogi/website#2]
# 🇮🇩 Indonesian
## Deskripsi
Issue ini digunakan untuk memantau proses translasi semua halaman. Issue akan ditutup ketika semua dokumentasi berhasil diselesaikan.

### Menjadi Penerjemah
1. Sebelum memulai, **pahami** dulu [panduan berkontribusi untuk penerjemah](https://github.com/grammyjs/website/blob/main/CONTRIBUTING.md#translations).
2. Terjemahkan dengan bahasa yang kamu kuasai. **JANGAN** hanya copas alias copy-paste mentah-mentah dari google translate. Gunakan pemahaman kamu agar menghasilkan terjemahan yang baik dan enak dibaca.
3. Ambil satu halaman yang belum diterjemahkan. Terus terjemahkan. Kalau sudah, buat pull request (PR) sesuai panduan di point satu di atas. Ingat, **satu PR untuk satu halaman** agar mudah dikerjakan dan dikoreksi.

### Menjadi Penyunting
Silahkan dikoreksi PR translasi yang sudah dibuat. Tambahkan catatan jika diperlukan.

## Catatan
Kata-kata yang berhubungan dengan _methods_, _function_ names, _variables_... **tidak perlu** diterjemahkan. Berikut beberapa contohnya:
```
bot
update
keyboard / inline keyboard
webhook
payload
... (dan lain-lain)
```

# 🇬🇧 English
## Description
This issue is for tracking the translation progress of all pages and will be closed when the documentation is finished.

### Being a translator
1. Read [how to contribute in translations](https://github.com/grammyjs/website/blob/main/CONTRIBUTING.md#translations)
2. Translate with your native-speaker level, **DO NOT** just copy the section to some translator tool and paste back the result
3. Take one untranslated page, translate and create PR from your fork to the main project. One PR for page, to better split in parallel the work and less tired reviews

### Being a reviewer
Find the PR's created for translations and review them. Add all notes that you consider.

## Note
Words related to _methods_, _function_ names, _variables_... **mustn't** be translated. Here are some examples:

```
bot
update
keyboard / inline keyboard
webhook
payload
... (feel free to add more, but make sense)
```
### README
- [x] [README.md](https://github.com/CikiMomogi/website/blob/main/site/docs/README.md)

### ADVANCED
- [ ] [deployment.md](https://github.com/CikiMomogi/website/blob/main/site/docs/advanced/deployment.md)
- [ ] [flood.md](https://github.com/CikiMomogi/website/blob/main/site/docs/advanced/flood.md)
- [ ] [middleware.md](https://github.com/CikiMomogi/website/blob/main/site/docs/advanced/middleware.md)
- [ ] [proxy.md](https://github.com/CikiMomogi/website/blob/main/site/docs/advanced/proxy.md)
- [ ] [README.md](https://github.com/CikiMomogi/website/blob/main/site/docs/advanced/README.md)
- [ ] [reliability.md](https://github.com/CikiMomogi/website/blob/main/site/docs/advanced/reliability.md)
- [ ] [scaling.md](https://github.com/CikiMomogi/website/blob/main/site/docs/advanced/scaling.md)
- [ ] [structuring.md](https://github.com/CikiMomogi/website/blob/main/site/docs/advanced/structuring.md)
- [ ] [transformers.md](https://github.com/CikiMomogi/website/blob/main/site/docs/advanced/transformers.md)

### Demo
- [ ]  [examples.md](https://github.com/grammyjs/website/blob/main/site/docs/es/demo/examples.md)
- [ ] [README.md](https://github.com/grammyjs/website/blob/main/site/docs/es/demo/README.md)

### Guide
- [ ] [api.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/api.md)
- [ ] [basics.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/basics.md)
- [ ] [commands.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/commands.md)
- [ ] [context.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/context.md)
- [ ] [deployment-types.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/deployment-types.md)
- [ ] [errors.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/errors.md)
- [ ] [files.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/files.md)
- [ ] [filter-queries.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/filter-queries.md)
- [ ] [games.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/games.md)
- [ ] [getting-started.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/getting-started.md)
- [ ] [inline-queries.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/inline-queries.md)
- [ ] [introduction.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/introduction.md)
- [ ] [middleware.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/middleware.md)
- [ ] [README.md](https://github.com/grammyjs/website/blob/main/site/docs/es/guide/README.md)

### Hosting
- [ ] [deno-deploy.md](https://github.com/grammyjs/website/blob/main/site/docs/es/hosting/deno-deploy.md)
- [ ] [gcf.md](https://github.com/grammyjs/website/blob/main/site/docs/es/hosting/gcf.md)
- [ ] [heroku.md](https://github.com/grammyjs/website/blob/main/site/docs/es/hosting/heroku.md)
- [ ] [vps.md](https://github.com/grammyjs/website/blob/main/site/docs/es/hosting/vps.md)

### Plugins
- [ ] [auto-retry.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/auto-retry.md)
- [ ] [command-filter.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/command-filter.md)
- [ ] [console-time.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/console-time.md)
- [ ] [files.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/files.md)
- [ ] [hydratate.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/hydratate.md)
- [ ] [i18n.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/i18n.md)
- [ ] [keyboard.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/keyboard.md)
- [ ] [menu.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/menu.md)
- [ ] [parse-mode.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/parse-mode.md)
- [ ] [ratelimiter.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/ratelimiter.md)
- [ ] [README.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/README.md) 
- [ ] [router.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/router.md)
- [ ] [runner.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/runner.md)
- [ ] [session.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/session.md)
- [ ] [stateless-question.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/stateless-question.md)
- [ ] [transformer-throttler.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/transformer-throttler.md)
- [ ] [emoji.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/emoji.md)
- [ ] [fluent.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/fluent.md)
- [ ] [guide.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/guide.md)
- [ ] [middlewares.md](https://github.com/grammyjs/website/blob/main/site/docs/es/plugins/middlewares.md)

### Resources
- [ ] [comparison.md](https://github.com/grammyjs/website/blob/main/site/docs/es/resources/comparison.md)
- [ ] [faq.md](https://github.com/grammyjs/website/blob/main/site/docs/es/resources/faq.md)
- [ ] [about.md](https://github.com/grammyjs/website/blob/main/site/docs/es/resources/about.md)
